Polygon changes
Instadapp/flashloan-aggregator pull request #45
Opened 2022-02-22 11:50 UTC by piyush2-0

2022-02-25 14:06 UTC, Vaibhav20201 requested changes

2022-02-25 14:06 UTC, Vaibhav20201 commented on contracts/aggregator/optimism/helpers.sol
> +    function setPoolAddress(address pool) internal {
Remove this

2022-02-25 14:06 UTC, Vaibhav20201 commented on contracts/aggregator/optimism/helpers.sol
> +    function calculateFeeBPS(uint256 _route)
Can remove for optimism

2022-02-25 14:06 UTC, Vaibhav20201 commented on contracts/aggregator/optimism/main.sol
> +            calculateFeeBPS(8)
Directly pass from pool key after factoring decimals

2022-02-25 16:02 UTC, Vaibhav20201 commented on contracts/aggregator/optimism/main.sol
> +            revert("this route is  not for optimism");
Lets remove this part.

2022-03-07 00:43 UTC, KaymasJain commented on contracts/aggregator/optimism/flashloan/main.sol
> +        bytes calldata _instadata // kept for future use by instadapp. Currently not used anywhere.
```suggestion
        bytes calldata _instadata
```

2022-03-07 01:10 UTC, KaymasJain approved these changes

2022-03-07 19:41 UTC, Vaibhav20201 approved these changes

2022-03-07 19:41 UTC, merged